#!/bin/sh

if [[ -z "$NPM_CMD" ]]; then
  NPM_CMD=start
fi

if [[ "$NODEMON" == "1" ]]; then
  npm prune && \
    npm ci && \
    nodemon --inspect=0.0.0.0:9229 -x npm $NPM_CMD
else
  npm prune && \
    npm ci && \
    npm $NPM_CMD
fi

